name: 'Terraform Plan for Development Environment'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch: 

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write

#These environment variables are used by the terraform azure provider to setup OIDD authenticate. 
env:
  WorkingDirectory: "./"
  TerraformVersion: "1.14.6" # Update to specific version if needed
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

  # terraform config
  ProjectNameInfra: "SyHunt" 
  TfStateName: "SyHunt-dev-francecentral.tfstate"

  # Terraform Backend Settings
  BackendSubscriptionId: ${{ secrets.BACKEND_SUBSCRIPTION_ID }}
  BackendRGName: ${{ secrets.BACKEND_RG_NAME }}
  BackendStorageAccountName: ${{ secrets.BACKEND_STORAGE_ACCOUNT_NAME }}
  BackendContainerName: ${{ secrets.BACKEND_CONTAINER_NAME }}
jobs:
  terraform-plan:
    name: 'Terraform Plan'
    environment: dev
    runs-on: ubuntu-latest  #self-hosted

    env:
      #this is needed since we are running terraform with read-only permissions
      ARM_SKIP_PROVIDER_REGISTRATION: true
    outputs:
      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout Modules Repo
      uses: actions/checkout@v4
      with:
        # Private Modules repo - requires PAT with repo scope
        repository: 'asasar/Modules' 
        ref: main
        path: 'Modules'
        token: ${{ secrets.MODULES_REPO_TOKEN }}
    - name: show folders
      run: |
        ls -R
        tree
    # Install the latest version of the Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TerraformVersion }}
        terraform_wrapper: false

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      working-directory: ${{ env.WorkingDirectory }}
      run: |
        terraform init \
            -backend-config="subscription_id=${{ env.BackendSubscriptionId }}" \
            -backend-config="resource_group_name=${{ env.BackendRGName }}" \
            -backend-config="storage_account_name=${{ env.BackendStorageAccountName }}" \
            -backend-config="container_name=${{ env.BackendContainerName }}" \
            -backend-config="key=${{ env.TfStateName }}"

    # Checks that all Terraform configuration files adhere to a canonical format
    # Will fail the build if not
    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ${{ env.WorkingDirectory }}

    # Generates an execution plan for Terraform
    # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
    - name: Terraform Plan
      id: tf-plan
      working-directory: ${{ env.WorkingDirectory }}
      run: |
        export exitcode=0
        terraform plan -detailed-exitcode -no-color -out tfplan -auto-approve --var-file=dev.tfvars || export exitcode=$?

        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
        
        if [ $exitcode -eq 1 ]; then
          echo Terraform Plan Failed!
          exit 1
        else 
          exit 0
        fi
        
    # Save plan to artifacts  
    - name: Publish Terraform Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: tfplan
        
    # Create string output of Terraform Plan
    - name: Create String Output
      id: tf-plan-string
      working-directory: ${{ env.WorkingDirectory }}
      run: |
        TERRAFORM_PLAN=$(terraform show -no-color tfplan)
        
        delimiter="$(openssl rand -hex 8)"
        echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
        echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
        echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo '```terraform' >> $GITHUB_OUTPUT
        echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
        echo '```' >> $GITHUB_OUTPUT
        echo "</details>" >> $GITHUB_OUTPUT
        echo "${delimiter}" >> $GITHUB_OUTPUT
        
    # Publish Terraform Plan as task summary
    - name: Publish Terraform Plan to Task Summary
      env:
        SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
      run: |
        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
      